name: McFacts
version: 2.0
author: Hessky
main: me.Hessky.McFacts.main
description: Get random facts about minecraft!

commands:
  facts:
    aliases: [fcs]
    description: Get 50 random facts about Minecraft! /fcs
  tiers:
    aliases: [trs]
    description: List of fact tiers (/trs)