name: McFacts
version: 1.0
author: Hessky
main: me.Hessky.McFacts.main
description: Get random facts about minecraft! It's interesting install the plugin plz.

commands:
  facts:
    aliases: [fcs]
    description: Get 24 random facts about Minecraft! Maybe some that you didn't know. Shortcut /fcs.