name: McFacts
version: 2.5
author: Hessky
main: me.Hessky.McFacts.main
description: Get random facts about minecraft!

commands:
  Facts:
    aliases: [fcs]
    description: Get 50 random facts about Minecraft (/fcs)
  Tiers:
    aliases: [trs]
    description: List of fact tiers (/trs)
  MCFactsReload:
    aliases: [mcfactsrl]
    description: Reload the config 
    